import { toIsoOffset } from "./electionEngine.js";

const avatar = (id) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=320&q=80`;

export function createDemoData() {
  const users = [
    {
      id: "u-admin",
      name: "Platform Admin",
      email: "admin@election.test",
      phone: "+92 300 0000001",
      role: "super_admin",
      verified: true,
    },
    {
      id: "u-creator",
      name: "Ayesha Khan",
      email: "creator@election.test",
      phone: "+92 300 0000002",
      role: "creator",
      organization: "National University Computing Society",
      verified: true,
      approved: true,
    },
    {
      id: "u-voter",
      name: "Demo Voter",
      email: "voter@election.test",
      phone: "+92 300 0000003",
      role: "voter",
      verified: true,
    },
  ];

  return {
    users,
    creatorRequests: [
      {
        id: "req-1",
        name: "Hamza Malik",
        email: "hamza@civics.org",
        phone: "+92 321 4447788",
        organization: "Civics Innovation Lab",
        purpose: "Run a transparent election for regional youth representatives.",
        status: "pending",
        rejectionReason: "",
        createdAt: toIsoOffset(-18),
      },
      {
        id: "req-2",
        name: "Nimra Javed",
        email: "nimra@alumni.edu",
        phone: "+92 321 1119090",
        organization: "University Alumni Network",
        purpose: "Conduct annual alumni board polling with authenticated voters.",
        status: "approved",
        rejectionReason: "",
        createdAt: toIsoOffset(-72),
      },
    ],
    elections: [
      {
        id: "poll-cs-president",
        codePrefix: "CS-PRES",
        creatorId: "u-creator",
        title: "Computer Science Society President",
        description:
          "Annual leadership vote for the Computer Science Society with anonymous ballots and live turnout.",
        category: "University",
        startAt: toIsoOffset(-2),
        endAt: toIsoOffset(7),
        registrationDeadline: toIsoOffset(-3),
        maxVoters: 1000,
        published: true,
        locked: true,
        finalizedVoterCount: 821,
        resultLocked: false,
        registrations: [
          {
            voterId: "u-voter",
            name: "Demo Voter",
            email: "voter@election.test",
            acceptedTerms: true,
            status: "finalized",
            secretId: "CS-PRES-0001-0003",
            voted: false,
            joinedAt: toIsoOffset(-48),
          },
        ],
        waitlist: [],
        candidates: [
          {
            id: "cand-zara",
            name: "Zara Ahmed",
            designation: "Final Year Representative",
            manifesto: "Expand mentorship circles, project showcases, and peer interview preparation.",
            photo: avatar("1494790108377-be9c29b29330"),
          },
          {
            id: "cand-bilal",
            name: "Bilal Raza",
            designation: "Programming Club Lead",
            manifesto: "Build weekly lab support hours and sponsor hackathon preparation tracks.",
            photo: avatar("1500648767791-00dcc994a43e"),
          },
          {
            id: "cand-sana",
            name: "Sana Iqbal",
            designation: "AI Study Group Organizer",
            manifesto: "Create inclusive study groups, open datasets, and research reading sessions.",
            photo: avatar("1531123897727-8f129e1688ce"),
          },
        ],
        votes: {
          "cand-zara": 382,
          "cand-bilal": 301,
          "cand-sana": 114,
        },
      },
      {
        id: "poll-robotics-board",
        codePrefix: "ROBO",
        creatorId: "u-creator",
        title: "Robotics Club Executive Board",
        description:
          "Multi-candidate executive board election for the next robotics lab planning cycle.",
        category: "Club",
        startAt: toIsoOffset(54),
        endAt: toIsoOffset(62),
        registrationDeadline: toIsoOffset(30),
        maxVoters: 300,
        published: true,
        locked: false,
        finalizedVoterCount: 0,
        resultLocked: false,
        registrations: [],
        waitlist: [],
        candidates: [
          {
            id: "cand-omer",
            name: "Omer Farooq",
            designation: "Embedded Systems Lead",
            manifesto: "Introduce beginner-friendly robot build nights and component lending.",
            photo: avatar("1507003211169-0a1dd7228f2d"),
          },
          {
            id: "cand-mehak",
            name: "Mehak Shah",
            designation: "Competition Coordinator",
            manifesto: "Prepare teams for national contests with structured milestones and reviews.",
            photo: avatar("1544005313-94ddf0286df2"),
          },
        ],
        votes: {
          "cand-omer": 0,
          "cand-mehak": 0,
        },
      },
      {
        id: "poll-hostel-council",
        codePrefix: "HOSTEL",
        creatorId: "u-creator",
        title: "Hostel Council Representatives",
        description:
          "Completed council election with final results locked for transparency review.",
        category: "Community",
        startAt: toIsoOffset(-40),
        endAt: toIsoOffset(-28),
        registrationDeadline: toIsoOffset(-52),
        maxVoters: 500,
        published: true,
        locked: true,
        finalizedVoterCount: 500,
        resultLocked: true,
        registrations: [],
        waitlist: [],
        candidates: [
          {
            id: "cand-hina",
            name: "Hina Saeed",
            designation: "Block A Representative",
            manifesto: "Improve study-room scheduling and maintenance request follow-through.",
            photo: avatar("1524504388940-b1c1722653e1"),
          },
          {
            id: "cand-daniyal",
            name: "Daniyal Qureshi",
            designation: "Sports Committee Volunteer",
            manifesto: "Bring fair booking slots and better weekend event coordination.",
            photo: avatar("1506794778202-cad84cf45f1d"),
          },
        ],
        votes: {
          "cand-hina": 271,
          "cand-daniyal": 196,
        },
      },
    ],
    auditLogs: [
      {
        id: "log-1",
        action: "approval",
        actor: "Platform Admin",
        detail: "Approved University Alumni Network creator request.",
        createdAt: toIsoOffset(-70),
        ipAddress: "demo-client",
      },
      {
        id: "log-2",
        action: "vote",
        actor: "Anonymous voter",
        detail: "Ballot recorded for Computer Science Society President.",
        createdAt: toIsoOffset(-1),
        ipAddress: "masked",
      },
      {
        id: "log-3",
        action: "finalization",
        actor: "Ayesha Khan",
        detail: "Finalized 821 voters and issued secret IDs for CS-PRES.",
        createdAt: toIsoOffset(-3),
        ipAddress: "demo-client",
      },
    ],
    notifications: [
      {
        id: "mail-1",
        type: "secret_id",
        recipient: "voter@election.test",
        subject: "Your secure voter ID for CS-PRES",
        status: "sent",
        createdAt: toIsoOffset(-3),
      },
      {
        id: "mail-2",
        type: "approval",
        recipient: "nimra@alumni.edu",
        subject: "Your election creator request was approved",
        status: "sent",
        createdAt: toIsoOffset(-70),
      },
    ],
  };
}
